### ISSUE TITLE
Add Pricelist to supplier

### ISSUE THREAD

**Issue by alexmagestore** [Magestore/SupplierSuccess#2]
If i chose "Add Pricelist to supplier" i get this error:

Unable to resolve the source file for 'adminhtml/Magento/backend/de_DE/Magestore_PurchaseOrderSuccess/template/form/components/button-list.html' #0 /var/www/html/vendor/magento/framework/App/StaticResource.php(97): Magento\Framework\View\Asset\File->getSourceFile() #1 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\StaticResource->launch() #2 /var/www/html/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource)) #3 {main}

**Comment by alexmagestore** [comment]
Fixed 1c0ab73d99d3550cd09605f00be90b85b1cbd0f0
